language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm install -g codecov
services:
  - postgresql
env:
  global:
    -NODE_ENV=test
    -CODECOV_TOKEN="93e09daf-902b-4e07-a341-7ce3b618d6a8"
  - npm run build
script:
  -npm test
