language: node_js
sudo: false
node_js:
- node
install:
- npm install
- npm install -g codecov
script:
- npm test
- npm run report-coverage
env:
  global:
    secure: nYmpdqw1fhooISdmlWl2gEnxQvdmsKxN6owvcD3QpbSjstYmeGRPxxG+8efQK12M4hmKMXW+3LJINpCdvvEVwoQnIw+rtqztUXPG1rgAIVLk+PtBJWP3A60EVJXc7RxR2+ww7U4zaRCP9q2ND99bX9ncDFmXk2oms27BIe7BSJC4DcYqcvasSvWT86dg9AQ8aX1jSBWU1ryxAiNx42TW3EA0ntJrskS/3hzQu8YsBwokvqA9FyeGznlVQJkruVNxma7SqSUA18ur11oWGNv8RtfNDuGAvmjrYw3SQL08KwjpbUsImzimbK4MGQPi9KhoCq/1Yp51QgaeyOW2pqxFu5KvF2r01t/mE13XM2iztv/MSB94vK+QCskGXrWq2+HU0eFT52YhKvfw0b1RQ7Re2vaBpVPD+jatyUBf9RXuqncOZI/aIc1u82ExNK820NxHPwI6/XJZXCOYiPPGtykwU6wxRSec5in6BzfZSwqPZjaVap5cIlRx3JqRIfPQ6BXfdlSOoS/qjEOFWxq32qHYHd1d0G9z2q/bAR7hAVHoTZUUYTrfc1skfUdgqy2l5NR8Wtc41jJTUsK282LJay70d3m9HP7Xgf/za7mjM3+uwhTeovRG1jRjAeBf00NM+pXP0yDTH8uIdJSrWwHvoChyktuYALf7wxndo3FjTls6FOs=
