language: node_js
sudo: false
node_js:
  - "node"
services:
  - postgresql
install:
  - "npm install"
  - "npm install -g codecov"                                                                                                       
script:
  - npm test
  - "npm run report-coverage"