language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
    -CODECOV_TOKEN="93e09daf-902b-4e07-a341-7ce3b618d6a8"
    -NODE_ENV=test
  - npm run build
script:
  -npm test
