language: node_js
node_js:
- node
services:
- postgresql
install:
- npm install
- npm install -g codecov
script:
- npm test
- npm run report-coverage
env:
  global:
  - secure: oKFzHkjkyE8A+meKx8Z5Ttd4WAU/t0IjkSlJ+CtGq90lQO5MtKHDFqskyavDq+bNkTvF3zbY+Mr7BVrgKIWK7dKHfhLTYNlQcjJbiBh0mwjjOuRkPGeCG2iLNqxmHibGrsgYxPSXL+xolvHj9Cga23w+xiAuG+cPPNHVzMxpFBa3x9iWJdNNahX5s5kl8GJZDX72ov0MaXSNScqplxekpGhrswvCLcfMFsmBoK7GpGugIKyzh3/aBiBos6iGYeKt5m96fMDEKUEx+fArHFEXhbfqVpmXJlv7nHm2sMhV3Jp5lgcyJKNDil+JzVK9KhqQ84VOAl1kH1xNXughmEu4SlpDwqig7r9g34YN4hUzBnFTbsRTNdm8lZcHjF2Dct8+FYkOlQodSeoClhYlXLRrT745ZFJxjAW6l+w1DVX018CBIy4/V4ZoXDxs8Uc+lHD/ub8eSSwQW9042ZyhhxEI/hvep+eAym3GKJc+nOUs7Yat/2ot1wm9+vEQ0LVHIc1vjcvnInPL+l9acdshg5+ZPBWXd030/jiC/EM9l7n6rHcmUuxdni2Kw5ldCvTYetSq2ke2afkprujg/fErUV0O9RpAT3yX3gD/HMeKUcbw+H/LApXgTlHno01EFVyUKb6mC4+0GLquVv2enLJnMjy2K2eupoywungp3uSivJxds1M=
