language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm install -g codecov
services:
  - postgresql
branches:
  - wk3
env:
  global:
    -NODE_ENV=test

  - npm run build
script:
  -npm test
